# 使用 Node.js 的官方映像作為基礎映像
FROM node:18

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json 到容器中
COPY package*.json ./

# 安裝應用程式的相依套件
RUN npm install

# 複製所有應用程式文件到容器中
COPY . .

# 定義容器啟動指令
CMD ["node", "app.js", "--port", "4000"]